Revert "Remove vim config, update setup for neovim"
This reverts commit f07e3248d4dcdff13c817a8303527d2400c1a449.

diff --git a/bin/nvim b/bin/nvim
--- a/bin/nvim
+++ b/bin/nvim
@@ -1,5 +1,13 @@
 #!/bin/bash
-# Command for running neovim
+# vim: set filetype=sh :
+
+# Purpose: Command for running neovim
+#
+# Set options:
+#   e: Stop script if command fails
+#   u: Stop script if unset variable is referenced
+#   x: Debug, print commands as they are executed
+#set -eu
 
 IMAGENAME=hyshka/neovim
 
@@ -11,12 +19,5 @@ else
   dir_name="$(pwd)"
 fi
 
-# Name container by tmux session
-name=$(tmux display-message -p '#S')
-timestamp=$(date +%s)
-
 # Run the docker command
-docker run -i -t -P -v "$dir_name":/root/app --name "nvim_${name}_${timestamp}" $IMAGENAME /bin/bash -c "cd /root/app; nvim $file_name"
-
-# Remove container after it's done
-docker rm $(docker ps -l -q)
+docker run --userns="host" -i -t -P -v "$dir_name":/src $IMAGENAME /bin/sh -c "cd /src;nvim $file_name"
